// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'it is not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'it is not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'it is not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyChnkC9SvZZ0ShMtAon1BqXPmpvvT3oIP8',
      appId: '1:912415959430:android:8928738850b072b391a407',
      messagingSenderId: '912415959430',
      projectId: 'univastay-467bd',
      storageBucket: 'univastay-467bd.appspot.com');

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBKNn0tKv4uKTNqHAKQH0_1bRs3WwJ4D-4",
      authDomain: "univastay-467bd.firebaseapp.com",
      projectId: "univastay-467bd",
      storageBucket: "univastay-467bd.appspot.com",
      messagingSenderId: "912415959430",
      appId: "1:912415959430:web:340a4f1baf290a7891a407");
}
